server:
  port: 9898
  servlet:
    context-path: /crm

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

# mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.dmw.crm.vo;com.dmw.crm.query;com.dmw.crm.dto
  configuration:
    map-underscore-to-camel-case: true

# pageHelper
pagehelper:
  reasonable: true # 分页合理
  helper-dialect: mysql # 方言

# 日志
logging:
  level:
    com:
      dmw:
        crm:
          dao: debug
